package com.education.android.mathcounts;
/**
 * @author Tynan
 * 
 * Card objects are equivalent to questions in the SQLite database. They are generated by the TestManager
 * at the beginning of each test and re-created when questions are queried from the database.
 * 
 */
public class Card {
	public static final String QUESTION_NUM = "question_number";  	//Represents index of card
	
	private int mFirstNum; 
	private int mSecondNum;
	private int mAnswer;
	private int mQuestionNum;
	
	private String mStudentAnswer = "";
	
	private boolean isViewed;
	
	public Card() {
		isViewed = false;
	}

	public int getFirstNum() {
		return mFirstNum;
	}

	public void setFirstNum(int firstNum) {
		mFirstNum = firstNum;
	}

	public int getSecondNum() {
		return mSecondNum;
	}

	public void setSecondNum(int secondNum) {
		mSecondNum = secondNum;
	}

	public boolean isViewed() {
		return isViewed;
	}

	public void setViewed(boolean isViewed) {
		this.isViewed = isViewed;
	}

	public int getAnswer() {
		return mAnswer;
	}

	public void setAnswer(int answer) {
		mAnswer = answer;
	}

	public int getQuestionNum() {
		return mQuestionNum;
	}

	public void setQuestionNum(int questionNum) {
		mQuestionNum = questionNum;
	}

	public String getStudentAnswer() {
		return mStudentAnswer;
	}

	public void setStudentAnswer(String studentAnswer) {
		mStudentAnswer = studentAnswer;
	}
}
